apiVersion: v1
kind: Namespace
metadata:
  name: t37
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: t37-web-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: t37-web-dep
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: t37-web-svc
  namespace: t37
spec:
  ports:
    - name: http
      port: 8443
      targetPort: 8443
  selector:
    app: t37-web-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t37-web-deb
  namespace: t37
spec:
  selector:
    matchLabels:
      app: t37-web-svc
  template:
    metadata:
      labels:
        app: t37-web-svc
    spec:
      containers:
        - image: docker.io/manimaul/t37.com:07-11-21_r0
          name: t37-web-svc
          ports:
            - containerPort: 8443
              name: http
          resources:
            requests:
              cpu: 100m
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    haproxy.org/server-ssl: "true"
    haproxy.org/ssl-redirect: "true" # https://www.haproxy.com/documentation/kubernetes/latest/configuration/ingress/
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: t37ingress
  namespace: t37
spec:
  rules:
    - host: t37.willkamp.com
      http:
        paths:
          - path: /
            backend:
              serviceName: t37-web-svc
              servicePort: 8443
  tls:
    - hosts:
        - t37.willkamp.com
      secretName: t37-cert
---
